.AUTODEPEND

#               *Translator Definitions*
CC = bcc +ICE16.CFG
TASM = TASM
TLIB = tlib
TLINK = tlink
LIBPATH = C:\BC45\LIB
INCLUDEPATH = C:\BC45\INCLUDE


#               *Implicit Rules*
.c.obj:
  $(CC) -c {$< }

.cpp.obj:
  $(CC) -c {$< }

#               *List Macros*


EXE_dependencies =  \
 a20.obj \
 app.obj \
 cpu.obj \
 dt.obj \
 gdt.obj \
 ioport.obj \
 main.obj \
 cpu32.obj \
 kernel.obj \
 mapi.obj \
 file.obj \
 string.obj \
 debug.obj

#               *Explicit Rules*
ice16.exe: ice16.cfg $(EXE_dependencies)
  $(TLINK) /v/k/m/3/c/L$(LIBPATH) @&&|
c0t.obj+
a20.obj+
app.obj+
cpu.obj+
dt.obj+
gdt.obj+
ioport.obj+
main.obj+
cpu32.obj+
kernel.obj+
mapi.obj+
file.obj+
string.obj+
debug.obj
ice16
		# no map file
cs.lib
|


#               *Individual File Dependencies*
a20.obj: ice16.cfg a20.cpp 

app.obj: ice16.cfg app.cpp 

cpu.obj: ice16.cfg cpu.cpp 

dt.obj: ice16.cfg dt.cpp 

gdt.obj: ice16.cfg gdt.cpp 

ioport.obj: ice16.cfg ..\ice32\ioport.cpp 

main.obj: ice16.cfg main.cpp 

cpu32.obj: ice16.cfg cpu32.asm 
        $(TASM) /M9 /T /MX /zn CPU32.ASM,CPU32.OBJ

kernel.obj: ice16.cfg kernel.asm 
        $(TASM) /M9 /T /MX /zn KERNEL.ASM,KERNEL.OBJ

mapi.obj: ice16.cfg pe\mapi.asm 
        $(TASM) /M9 /T /MX /zn PE\MAPI.ASM,MAPI.OBJ

debug.obj: ice16.cfg debug.asm
		$(TASM) /M9 /T /MX /zn DEBUG.ASM,DEBUG.OBJ

file.obj: ice16.cfg ..\..\library\libcpp\file.cpp 
        $(CC) -c ..\..\library\libcpp\file.cpp

string.obj: ice16.cfg ..\..\library\libcpp\string.cpp 
        $(CC) -c ..\..\library\libcpp\string.cpp

#               *Compiler Configuration File*
ice16.cfg: makefile.
  copy &&|
-v
-mt
-3
-f-
-y
-vi-
-wpro
-weas
-wpre
-I$(INCLUDEPATH)
-L$(LIBPATH)
| ice16.cfg


